window.ER_BOSSES = [

    {
    id: 'grafted-scion', category: 'field',
    image: './img/scion.webp',
    en: { name: 'Grafted Scion', quote: '"..."', region: 'Limgrave',
      lore: 'A lesser grafted creature serving Godrick\'s lineage, the Scion is an early test of combat in the Chapel of Anticipation and an optional boss in Fringefolk Hero\'s Grave.',
      location: 'Chapel of Anticipation (tutorial) or Fringefolk Hero\'s Grave at Limgrave starting beach.',
      mapDesc: 'Starting area beach cave on the east, or tutorial zone before Limgrave proper.',
      grace: 'Nearest Site of Grace: Church of Elleh (after reaching Limgrave).',
      strategy: ['Use Storm Stomp Ash of War to stagger repeatedly', 'Fight on the stairs in Hero\'s Grave for elevation advantage', 'Roll through vine whip attacks', 'Fire damage is effective against grafted enemies', 'Can be skipped entirely via side path in Hero\'s Grave'] },
    pl: { name: 'Spleciony Potomek', quote: '"..."', region: 'Limgrave',
      lore: 'Mniejsza spleciona istota z linii Godricka. Wczesny test walki.',
      location: 'Kaplica Antycypacji lub Fringefolk Hero\'s Grave.',
      mapDesc: 'Jaskinia na startowej plaży Limgrave.',
      grace: 'Obóz: Kościół Elleh.',
      strategy: ['Storm Stomp do stagger', 'Walcz na schodach', 'Przetaczaj przez pnącza', 'Ogień skuteczny', 'Można pominąć boczną ścieżką'] },
    de: { name: 'Gepfropfter Spross', quote: '"..."', region: 'Limgrave',
      lore: 'Ein gepfropftes Wesen in Godricks Linie. Früher Kampftest.',
      location: 'Kapelle der Erwartung oder Fringefolk-Heldengrab.',
      mapDesc: 'Höhle am Startstrand von Limgrave.',
      grace: 'Sammelpunkt: Kirche von Elleh.',
      strategy: ['Storm Stomp für Stagger', 'Auf Treppen kämpfen', 'Durch Rankenhiebe rollen', 'Feuerschaden wirksam', 'Via Seitenweg überspringbar'] }
  },

  {
    id: 'margit', category: 'shard',
    image: './img/Margit.webp',
    en: { name: 'Margit, the Fell Omen', quote: '"Well, thou art of little worth, fraud."', region: 'Limgrave',
      lore: 'Margit is a spectral Omen who guards Stormveil Castle against Tarnished seeking audience with Godrick. He serves as the first major gatekeeper of the Lands Between, testing whether the player is worthy of the Elden Throne.',
      location: 'Stormveil Castle entrance bridge, Limgrave. Accessible after reaching the castle from the Stormhill side or through the side path from the Deathtouched Catacombs.',
      mapDesc: 'Found at the northern edge of Limgrave where the path ascends toward Stormveil Castle. Look for the great bridge guarded by a golden fog gate.',
      grace: 'Nearest Site of Grace: Margit, the Fell Omen (appears after defeat) or Castleward Tunnel.',
      strategy: ['Use Spirit Ash summons like Lone Wolf or Omenkiller for distraction', 'Roll toward Margit during delayed tail and hammer swings', 'Use a 100% physical shield for his dagger flurry combo', 'Bloodhound Step or Crucible Hornshield trivializes many attacks', 'Stay at medium range and punish his long recovery after jump attacks'] },
    pl: { name: 'Margit, Upadły Omen', quote: '"Cóż, jesteś małej wartości, oszust."', region: 'Limgrave',
      lore: 'Margit to widmowy Omen strzegący Zamku Burzowego przed Zhańbionymi. Jest pierwszym poważnym strażnikiem Krain Pomiędzy.',
      location: 'Most przy wejściu do Zamku Burzowego, Limgrave.',
      mapDesc: 'Na północnym krańcu Limgrave, przy wielkim moście prowadzącym do zamku.',
      grace: 'Najbliższy Obóz: Margit (po pokonaniu) lub Tunel Zamkowy.',
      strategy: ['Przywołaj ducha Omenkillera lub wilki', 'Przetaczaj się w kierunku Margita przy opóźnionych atakach', 'Tarcza 100% fizycznej ochrony na combo sztyletów', 'Bloodhound Step ułatwia uniki', 'Karaj długie animacje po skokach'] },
    de: { name: 'Margit, der Üble Omen', quote: '"Nun, du bist wenig wert, Betrüger."', region: 'Limgrave',
      lore: 'Margit ist ein spektraler Omen, der Sturmwindfeste bewacht. Er ist der erste große Wächter der Zwischenlande.',
      location: 'Sturmwindfeste-Brücke, Limgrave.',
      mapDesc: 'Am nördlichen Rand von Limgrave an der großen Brücke zur Feste.',
      grace: 'Nächster Sammelpunkt: Margit (nach Sieg) oder Festungsweg-Tunnel.',
      strategy: ['Geisterasche wie Omenkiller beschwören', 'In Richtung Margit rollen bei verzögerten Angriffen', '100% physisches Schild für Dolch-Kombo', 'Bloodhound Step erleichtert Ausweichen', 'Lange Recovery nach Sprüngen bestrafen'] }
  },
  {
    id: 'godrick', category: 'shard',
    image: './img/Godrick.webp',
    en: { name: 'Godrick the Grafted', quote: '"A lowly Tarnished, playing lord. How amusing."', region: 'Stormveil Castle',
      lore: 'Godrick is a demigod and shardbearer who grafts the limbs of heroes onto his body. Weak among the demigods, he hides in Stormveil and collects body parts to gain strength, yet remains a cruel tyrant of Limgrave.',
      location: 'Top of Stormveil Castle, accessed through the main path or the rooftop shortcut via Rusty Key.',
      mapDesc: 'Deep inside Stormveil Castle at the throne room arena. The castle sits between Limgrave and Stormhill.',
      grace: 'Nearest Site of Grace: Secluded Cell (inside castle) or Rampart Tower.',
      strategy: ['Use Nepheli Loux summon for phase 1 assistance', 'Stay close to his legs in phase 2 to avoid wind attacks', 'Bloodhound Step dodges his delayed axe slams', 'Focus on his grafted dragon arm — it is his main threat', 'Roll into him during fire breath rather than away'] },
    pl: { name: 'Godrick Spleciony', quote: '"Podły Zhańbiony udający pana. Jakie to zabawne."', region: 'Zamek Burzowy',
      lore: 'Godrick to półbóg łączący kończyny bohaterów ze swoim ciałem. Ukrywa się w Zamku Burzowym i zbiera części ciał by zyskać siłę.',
      location: 'Szczyt Zamku Burzowego, sala tronowa.',
      mapDesc: 'Głęboko w zamku między Limgrave a Stormhill.',
      grace: 'Obóz: Odosobniona Cela lub Wieża Wału.',
      strategy: ['Przywołaj Nepheli Loux', 'W fazie 2 trzymaj się blisko nóg', 'Unikaj opóźnionych ciosów toporem', 'Skup się na smoczej ręce', 'Przetaczaj się w stronę ognia, nie od niego'] },
    de: { name: 'Godrick der Gepfropfte', quote: '"Ein niederer Befleckter spielt Herr. Wie amüsant."', region: 'Sturmwindfeste',
      lore: 'Godrick ist ein Halbgott, der Heldengliedmaßen aufpfropft. Er versteckt sich in Sturmwindfeste und sammelt Körperteile.',
      location: 'Thronraum auf der Spitze der Sturmwindfeste.',
      mapDesc: 'Tief in der Feste zwischen Limgrave und Sturmhügel.',
      grace: 'Sammelpunkt: Abgeschiedene Zelle oder Wallturm.',
      strategy: ['Nepheli Loux rufen', 'In Phase 2 nah an den Beinen bleiben', 'Verzögerte Axthiebe ausweichen', 'Drachenarm ist Haupthreat', 'In Feueratmung hineinrollen'] }
  },
    {
    id: 'red-wolf', category: 'field',
    image: './img/wolf.webp',
    en: { name: 'Red Wolf of Radagon', quote: '"..."', region: 'Liurnia',
      lore: 'A spectral wolf of Radagon that guards the academy approaches. It combines swift swordplay with glintstone sorcery, serving as Rennala\'s loyal hound at the school gates.',
      location: 'Raya Lucaria Academy gate, eastern Liurnia. Also found in Consecrated Snowfield.',
      mapDesc: 'East of the academy island in Liurnia, before the main academy gate.',
      grace: 'Nearest Site of Grace: Academy Gate Town or Temple Quarter.',
      strategy: ['Use shield for sword combo then counter', 'Roll toward wolf not away — it closes distance fast', 'Spirit summons distract during sorcery phase', 'Bloodhound Step for magic sword lunges', 'Greatshield users can block most attacks safely'] },
    pl: { name: 'Czerwony Wilk Radagona', quote: '"..."', region: 'Liurnia',
      lore: 'Widmowy wilk Radagona strzegący akademii. Łączy miecz z magią.',
      location: 'Brama Akademii Raya Lucaria, wschodnia Liurnia.',
      mapDesc: 'Na wschód od wyspy akademii.',
      grace: 'Obóz: Miasto Bramy Akademii.',
      strategy: ['Tarcza na combo miecza', 'Przetaczaj w wilka', 'Duch na fazę magii', 'Bloodhound Step na wypady', 'Wielka tarcza bezpieczna'] },
    de: { name: 'Roter Wolf Radagons', quote: '"..."', region: 'Liurnia',
      lore: 'Radagons spektraler Wolf bewacht die Akademie. Schwert und Glintstein-Magie.',
      location: 'Akademie-Tor Raya Lucaria, östliches Liurnia.',
      mapDesc: 'Östlich der Akademie-Insel.',
      grace: 'Sammelpunkt: Akademie-Tor-Stadt.',
      strategy: ['Schild gegen Schwertcombo', 'In Richtung Wolf rollen', 'Geisterasche bei Magie', 'Bloodhound Step bei Stößen', 'Großschild sicher'] }
  },
  {
    id: 'rennala', category: 'shard',
    image: './img/Queen.webp',
    en: { name: 'Rennala, Queen of the Full Moon', quote: '"I am Rennala, Queen of the Full Moon."', region: 'Liurnia of the Lakes',
      lore: 'Rennala is the head of the Academy of Raya Lucaria and mother of demigods. After Radagon left her, she fell into grief and was protected by her students. She governs rebirth through the Great Rune she holds.',
      location: 'Raya Lucaria Academy, Church of the Cuckoo. Requires Academy Glintstone Key from Thops or stolen from Sellen.',
      mapDesc: 'Central Liurnia — the academy rises from the lake. Enter through the main gate after obtaining the key.',
      grace: 'Nearest Site of Grace: Church of the Cuckoo.',
      strategy: ['Phase 1: kill golden students to break her shield, ignore adds', 'Use Rock Sling or Glintstone Pebble for consistent damage', 'Phase 2: stay mobile and dodge moon sorceries', 'Carian Retaliation can parry her magic', 'Spirit summons like Mimic Tear dominate phase 2'] },
    pl: { name: 'Rennala, Królowa Pełni Księżyca', quote: '"Jestem Rennala, Królowa Pełni Księżyca."', region: 'Liurnia Jezior',
      lore: 'Rennala kieruje Akademią Raya Lucaria. Po odejściu Radagona pogrążyła się w żalu. Włada odrodzeniem dzięki Wielkiemu Odłamkowi.',
      location: 'Akademia Raya Lucaria, Kościół Kukułki.',
      mapDesc: 'Centralna Liurnia — akademia na jeziorze.',
      grace: 'Obóz: Kościół Kukułki.',
      strategy: ['Faza 1: zabij złotych uczniów by złamać tarczę', 'Używaj Rock Sling', 'Faza 2: unikaj magii księżyca', 'Carian Retaliation parry magic', 'Mimic Tear dominuje fazę 2'] },
    de: { name: 'Rennala, Königin des Vollmonds', quote: '"Ich bin Rennala, Königin des Vollmonds."', region: 'Liurnia der Seen',
      lore: 'Rennala leitet die Akademie Raya Lucaria. Nach Radagons Abgang verfiel sie in Trauer und hält den Großen Runensplitter der Wiedergeburt.',
      location: 'Akademie Raya Lucaria, Kuckuckskirche.',
      mapDesc: 'Zentrales Liurnia — die Akademie im See.',
      grace: 'Sammelpunkt: Kuckuckskirche.',
      strategy: ['Phase 1: goldene Schüler töten für Schildbruch', 'Rock Sling nutzen', 'Phase 2: Mondmagie ausweichen', 'Carian Retaliation pariert', 'Mimic Tear in Phase 2'] }
  },

    {
    id: 'radahn', category: 'shard',
    image: './img/Radahn.webp',
    en: { name: 'Starscourge Radahn', quote: '"The stars have aligned, Tarnished."', region: 'Caelid',
      lore: 'Radahn is the mightiest demigod warrior who conquered the stars themselves using gravity magic taught by an Alabaster Lord. The Scarlet Rot ravages his mind and body, yet he still rides his beloved horses Leonard and child-of-stars in eternal battle.',
      location: 'Redmane Castle festival arena, southeastern Caelid. Activate festival by talking to Jerren at the castle.',
      mapDesc: 'Southeast Caelid at Redmane Castle. The arena opens after progressing Ranni or Radahn questlines.',
      grace: 'Nearest Site of Grace: Chamber Outside the Plaza (inside castle).',
      strategy: ['Use Torrent and run in circles during meteor phase — do NOT fight on foot', 'Summon all NPC signs before entering (Blaidd, Alexander, etc.)', 'Apply Rot or Frost for passive damage', 'Use Greatbow from horseback to weaken before dismount', 'Bloodhound Step or Starscourge Heirloom helps with gravity slams'] },
    pl: { name: 'Radahn Kosmicznej Plagi', quote: '"Gwiazdy się wyrównały, Zhańbiony."', region: 'Caelid',
      lore: 'Radahn to najpotężniejszy wojownik półbogów, który opanował magię grawitacji. Skaza Szkarłatna niszczy jego ciało i umysł.',
      location: 'Arena festiwalu Zamku Czerwonej Grzywy, południowy wschód Caelid.',
      mapDesc: 'Południowo-wschodnie Caelid przy zamku Redmane.',
      grace: 'Obóz: Komnata przed Placzem.',
      strategy: ['Podczas meteorytów galopuj na Torrent w kółko', 'Przywołaj wszystkich NPC przed walką', 'Nałóż Rot lub Frost', 'Osłab wielkim łukiem z konia', 'Bloodhound Step na uderzenia grawitacji'] },
    de: { name: 'Sternenplage Radahn', quote: '"Die Sterne stehen günstig, Befleckter."', region: 'Caelid',
      lore: 'Radahn ist der mächtigste Halbgott-Krieger, der die Sterne mit Gravitationsmagie bezwingt. Scharlachfäule zehrt an ihm.',
      location: 'Festarena der Rotmähnen-Feste, südöstliches Caelid.',
      mapDesc: 'Südost-Caelid bei Rotmähnen-Feste.',
      grace: 'Sammelpunkt: Kammer vor dem Platz.',
      strategy: ['Bei Meteorit regen auf Torrent im Kreis reiten', 'Alle NPC-Beschwörungen nutzen', 'Fäulnis oder Frost anwenden', 'Mit Großbogen vom Pferd schwächen', 'Bloodhound Step bei Gravitationsschlägen'] }
  },
      {
    id: 'rykard', category: 'shard',
    image: './img/rykard.webp',
    en: { name: 'Rykard, Lord of Blasphemy', quote: '"Join the Serpent King, as family."', region: 'Mt. Gelmir',
      lore: 'Rykard devoured the god-devouring serpent and became one with it, founding the Volcano Manor cult. He blasphemed against the Greater Will and sought to create a new order where all could be devoured and reborn as one.',
      location: 'Volcano Manor, Temple of Eiglay. Use Serpent-Hunter spear found in the manor.',
      mapDesc: 'Mt. Gelmir region west of Altus Plateau. Enter Volcano Manor via invitation or Abductor Virgin shortcut.',
      grace: 'Nearest Site of Grace: Temple of Eiglay or Guest Hall.',
      strategy: ['MUST equip Serpent-Hunter spear — it deals massive bonus damage', 'Hit Rykard\'s head not the snake body', 'Use Mimic Tear or Black Knife Tiche', 'Stay near the head during fire phases', 'Phase 2: attack during serpent slam recovery windows'] },
    pl: { name: 'Rykard, Pan Blasphemii', quote: '"Dołącz do Króla Węży, jak rodzina."', region: 'Mt. Gelmir',
      lore: 'Rykard połączył się z wężem pożerającym bogów i założył kult Volcano Manor. Blafemował przeciw Wielkiej Woli.',
      location: 'Volcano Manor, Świątynia Eiglay. Użyj włóczni Serpent-Hunter.',
      mapDesc: 'Mt. Gelmir na zachód od Altus Plateau.',
      grace: 'Obóz: Świątynia Eiglay.',
      strategy: ['Obowiązkowo Serpent-Hunter — bonusowe obrażenia', 'Atakuj głowę Rykarda', 'Przywołaj Mimic Tear', 'Przy głowie podczas ognia', 'Karaj po uderzeniach węża'] },
    de: { name: 'Rykard, Herr der Blasphemie', quote: '"Schließe dich dem Schlangenkönig an, als Familie."', region: 'Mt. Gelmir',
      lore: 'Rykard verschmolz mit der gottverschlingenden Schlange und gründete den Vulkan-Manor-Kult.',
      location: 'Vulkan-Manor, Tempel von Eiglay. Schlangenjäger-Speer nutzen.',
      mapDesc: 'Mt. Gelmir westlich des Altus-Plateaus.',
      grace: 'Sammelpunkt: Tempel von Eiglay.',
      strategy: ['Schlangenjäger-Speer ist Pflicht', 'Rykards Kopf treffen', 'Mimic Tear rufen', 'Nahe am Kopf bei Feuer', 'Recovery nach Schlangenhieben nutzen'] }
  },
    {
    id: 'loretta', category: 'legend',
    image: './img/loretta.webp',
    en: { name: 'Loretta, Knight of the Haligtree', quote: '"..."', region: 'Liurnia / Haligtree',
      lore: 'Loretta is a royal knight who serves the Haligtree and Miquella. A master of sorcery and greatbow, she guards the path to the Haligtree as both a boss in the Royal Capital and at the Haligtree itself.',
      location: 'Royal Knight Loretta in Caria Manor, Liurnia. Knight Loretta at Haligtree Promenade.',
      mapDesc: 'Caria Manor in northwest Liurnia, or Haligtree Promenade in the northern region.',
      grace: 'Nearest Site of Grace: Manor Lower Level or Haligtree Promenade.',
      strategy: ['Use Shield of the Guilty or Spell Parry on her magic', 'Close distance quickly to prevent greatbow sniping', 'Roll toward her teleport slash not away', 'Spirit Ash helps in Caria Manor version', 'Magic-resistant gear for Haligtree version'] },
    pl: { name: 'Loretta, Rycerz Haligtree', quote: '"..."', region: 'Liurnia / Haligtree',
      lore: 'Loretta to królewski rycerz służący Haligtree i Miquelli. Mistrzyni magii i wielkiego łuku.',
      location: 'Caria Manor w Liurnia lub Promenada Haligtree.',
      mapDesc: 'Północno-zachodnia Liurnia lub północ Haligtree.',
      grace: 'Obóz: Dolny Poziom Dworu.',
      strategy: ['Spell Parry na magię', 'Zmniejsz dystans szybko', 'Przetaczaj w teleport slash', 'Duch w wersji z Caria Manor', 'Odporność na magię w Haligtree'] },
    de: { name: 'Loretta, Ritter des Haligbaums', quote: '"..."', region: 'Liurnia / Haligbaum',
      lore: 'Loretta ist eine königliche Ritterin des Haligbaums und Miquellas. Meisterin der Magie und des Großbogens.',
      location: 'Caria-Manor in Liurnia oder Haligbaum-Promenade.',
      mapDesc: 'Nordwest-Liurnia oder nördlicher Haligbaum.',
      grace: 'Sammelpunkt: Unteres Manor-Level.',
      strategy: ['Zauberpariere gegen Magie', 'Schnell näher kommen', 'In Teleport-Hieb rollen', 'Geisterasche in Caria Manor', 'Magieresistenz im Haligbaum'] }
  },

    {
    id: 'ancestor', category: 'field',
    image: './img/ancesstor.webp',
    en: { name: 'Ancestor Spirit', quote: '"..."', region: 'Limgrave / Siofra River',
      lore: 'The Ancestor Spirits are revered beings of the Eternal City and Siofra River. They phase in and out of existence, representing the spiritual heritage of the Numen and ancient beastmen.',
      location: 'Siofra River Bank (Limgrave well) or Siofra Aqueduct (Nokron). Requires Stargazer fragments to unlock boss gate.',
      mapDesc: 'Underground Siofra River accessed via Mistwood Ruins well or Blaidd\'s quest in Nokron.',
      grace: 'Nearest Site of Grace: Siofra River Bank or Aqueduct-Facing Cliffs.',
      strategy: ['Use Spirit Summons Ash — boss is weak to summoning thematic damage', 'Watch for phase-out: stop attacking when transparent', 'Bleed and frost work well when corporeal', 'Roll through charge attack not away', 'Second phase adds more aggressive combos — stay patient'] },
    pl: { name: 'Duch Przodków', quote: '"..."', region: 'Siofra River',
      lore: 'Duchy Przodków to czczone istoty Wiecznego Miasta i Rzeki Siofra.',
      location: 'Brzeg Siofra River lub Akwedukt Siofra.',
      mapDesc: 'Podziemna Siofra przez studnię Mistwood.',
      grace: 'Obóz: Brzeg Siofra River.',
      strategy: ['Użyj duchów — boss słaby tematycznie', 'Przestań atakować gdy przezroczysty', 'Bleed i frost działają', 'Przetaczaj przez szarżę', 'Faza 2 bardziej agresywna'] },
    de: { name: 'Ahnengeist', quote: '"..."', region: 'Siofra-Fluss',
      lore: 'Ahnengeister sind verehrte Wesen der Ewigen Stadt und des Siofra-Flusses.',
      location: 'Siofra-Flussufer oder Siofra-Aquädukt.',
      mapDesc: 'Unterirdischer Siofra-Fluss via Mistwood-Brunnen.',
      grace: 'Sammelpunkt: Siofra-Flussufer.',
      strategy: ['Geisterasche nutzen', 'Nicht angreifen wenn transparent', 'Blutung und Frost wirken', 'Durch Angriff rollen', 'Phase 2 geduldig spielen'] }
  },
    {
    id: 'astel', category: 'legend',
    image: './img/astel.webp',
    en: { name: 'Astel, Naturalborn of the Void', quote: '"..."', region: 'Lake of Rot / Deeproot Depths',
      lore: 'Astel is a malformed star of the void who descended upon the Lands Between. It destroyed an Eternal City and left the Lake of Rot in its wake, a cosmic horror born from outer darkness.',
      location: 'Grand Cloister at Lake of Rot, or Yelough Anix Tunnel in Consecrated Snowfield.',
      mapDesc: 'Two copies exist — one at the bottom of Lake of Rot (via Astel tunnel), one in Consecrated Snowfield tunnel.',
      grace: 'Nearest Site of Grace: Grand Cloister or Yelough Anix Tunnel.',
      strategy: ['Stay under Astel during meteor shower — it misses you', 'Run to tail when it teleports for easy hits', 'Rock Sling or Comet Azur for consistent magic damage', 'Bloodhound Step dodges tail swipe and charge', 'Phase 2 void explosion: run away then re-engage'] },
    pl: { name: 'Astel, Urodzony z Pustki', quote: '"..."', region: 'Jezioro Zgnilizny',
      lore: 'Astel to zdeformowana gwiazda z pustki. Zniszczył Wieczne Miasto i pozostawił Jezioro Zgnilizny.',
      location: 'Wielki Klasztor przy Jeziorze Zgnilizny lub Tunel Yelough Anix.',
      mapDesc: 'Dno Jeziora Zgnilizny lub Consecrated Snowfield.',
      grace: 'Obóz: Wielki Klasztor.',
      strategy: ['Schowaj się pod Astel podczas meteorytów', 'Biegnij do ogona po teleportacji', 'Rock Sling lub Comet Azur', 'Bloodhound Step na ogon', 'Po eksplozji uciekaj i wracaj'] },
    de: { name: 'Astel, Natürlicher der Leere', quote: '"..."', region: 'See der Fäulnis',
      lore: 'Astel ist ein missgestalteter Stern der Leere, der eine Ewige Stadt zerstörte.',
      location: 'Großer Kreuzgang am See der Fäulnis oder Yelough-Anix-Tunnel.',
      mapDesc: 'Grund des Sees der Fäulnis oder Heiliger Schnee.',
      grace: 'Sammelpunkt: Großer Kreuzgang.',
      strategy: ['Unter Astel bei Meteoritregen verstecken', 'Zum Schwanz nach Teleport rennen', 'Rock Sling oder Komet Azur', 'Bloodhound Step gegen Schwanz', 'Nach Explosion zurückkehren'] }
  },
    {
    id: 'golden-godfrey', category: 'field',
    image: './img/Godfrey.webp',
    en: { name: 'Golden Godfrey', quote: '"A warrior, after all."', region: 'Leyndell, Royal Capital',
      lore: 'The golden shade of Godfrey appears when you have enough Great Runes. He tests the Tarnished before allowing access to the Erdtree, representing Godfrey at the height of his power as Elden Lord.',
      location: 'Capital Outskirts grace area, Leyndell. Appears after collecting 2+ Great Runes.',
      mapDesc: 'Just outside Leyndell at the Capital Outskirts, near the giant fallen Erdtree branch.',
      grace: 'Nearest Site of Grace: Capital Rampart or Outer Wall Phantom Tree.',
      strategy: ['Use Barricade Shield on Greatshield', 'Roll toward axe swings', 'His war cry buffs himself — use the window after to attack', 'Bloodhound Step for stomp attacks', 'Do not get greedy during golden slam combo'] },
    pl: { name: 'Złoty Godfrey', quote: '"Wojownik, w końcu."', region: 'Leyndell',
      lore: 'Złoty cień Godfreya testuje Zhańbionych przed dostępem do Drzewa Erd.',
      location: 'Przedmieścia Stolicy, po zebraniu 2+ Wielkich Odłamków.',
      mapDesc: 'Przed Leyndell przy Capital Outskirts.',
      grace: 'Obóz: Wał Stolicy.',
      strategy: ['Barricade Shield na wielkiej tarczy', 'Przetaczaj w topór', 'Atakuj po okrzyku wojennym', 'Bloodhound Step na stomp', 'Nie chciwo przy złotym combo'] },
    de: { name: 'Goldener Godfrey', quote: '"Ein Krieger, schließlich."', region: 'Leyndell',
      lore: 'Godfreys goldener Schatten testet Befleckte vor dem Erdbaumzugang.',
      location: 'Hauptstadt-Vororte nach 2+ Großen Runensplittern.',
      mapDesc: 'Vor Leyndell bei den Hauptstadt-Vororten.',
      grace: 'Sammelpunkt: Hauptstadtwall.',
      strategy: ['Barricade Shield auf Großschild', 'In Axthiebe rollen', 'Nach Kriegsschrei angreifen', 'Bloodhound Step bei Stampfer', 'Nicht gierig bei goldenem Combo'] }
  },
    {
    id: 'morgott', category: 'shard',
    image: './img/Morgott.webp',
    en: { name: 'Morgott, the Omen King', quote: '"I am Morgott, the Omen King."', region: 'Leyndell, Royal Capital',
      lore: 'Morgott is the twin of Margit and true ruler of Leyndell who never left the capital. He guards the Erdtree from all Tarnished and hides his Omen form beneath a golden illusion, ruling as the Veiled Monarch.',
      location: 'Erdtree Sanctuary, Leyndell Royal Capital. Reach via Grand Lift of Dectus or Fellgate.',
      mapDesc: 'Heart of Leyndell at the Erdtree Sanctuary altar. The capital lies at the center of the Lands Between map.',
      grace: 'Nearest Site of Grace: Queen\'s Bedchamber or Erdtree Sanctuary.',
      strategy: ['Use Mohg\'s Shackle 3 times at start of each phase for free damage', 'Roll toward delayed hammer swings', 'Stay close to prevent spear thrust spam', 'Bloodhound Step trivializes most attacks', 'Phase 2 wings: roll through fire not away from it'] },
    pl: { name: 'Morgott, Król Omenów', quote: '"Jestem Morgott, Król Omenów."', region: 'Leyndell',
      lore: 'Morgott to brat bliźniak Margita i prawdziwy władca Leyndell. Strzeże Drzewa Erd i ukrywa formę Omena za złotą iluzją.',
      location: 'Sanktuarium Drzewa Erd, Leyndell.',
      mapDesc: 'Centrum mapy — stolica Leyndell.',
      grace: 'Obóz: Komnata Królowej lub Sanktuarium Drzewa Erd.',
      strategy: ['Użyj Kajdanek Mohga 3 razy na początku faz', 'Przetaczaj się w stronę młota', 'Trzymaj bliską odległość', 'Bloodhound Step na większość ataków', 'Przetaczaj się przez ogień skrzydeł'] },
    de: { name: 'Morgott, König der Omen', quote: '"Ich bin Morgott, König der Omen."', region: 'Leyndell',
      lore: 'Morgott ist Margits Zwillingsbruder und wahrer Herrscher von Leyndell. Er bewacht den Erdbaum hinter einer goldenen Illusion.',
      location: 'Erdbaumsanktuar, Leyndell.',
      mapDesc: 'Zentrum der Karte — Hauptstadt Leyndell.',
      grace: 'Sammelpunkt: Königinnenschlafgemach oder Erdbaumsanktuar.',
      strategy: ['Mohgs Fessel 3x zu Phasenbeginn', 'In Hammerhiebe hineinrollen', 'Nah bleiben gegen Speer', 'Bloodhound Step nutzen', 'Durch Flügelfeuer rollen'] }
  },

  {
    id: 'fire-giant', category: 'legend',
    image: './img/giant.webp',
    en: { name: 'Fire Giant', quote: '"Burn... the Erdtree..."', region: 'Flame Peak',
      lore: 'The last of the Fire Giants who betrayed their kin to serve the Erdtree. Bound by a one-eyed helm, he guards the Flame of Ruin needed to burn the Erdtree and advance the main story.',
      location: 'Flame Peak, Mountaintops of the Giants. Northern path from Forge of the Giants grace.',
      mapDesc: 'Northern Mountaintops of the Giants at Flame Peak. Visible giant arena on the mountainside.',
      grace: 'Nearest Site of Grace: Foot of the Forge.',
      strategy: ['Use Torrent and stay on horseback for entire fight', 'Target the ankle with bleed or frost weapons', 'During snowball phase: ride perpendicular and re-approach', 'Spirit summons like Mimic on foot while you stay mounted', 'Greatbow from horseback for safe chip damage'] },
    pl: { name: 'Ognisty Olbrzym', quote: '"Spal... Drzewo Erd..."', region: 'Flame Peak',
      lore: 'Ostatni z Ognistych Olbrzymów, który zdradził swóch by służyć Drzewu Erd. Strzeże Płomienia Ruiny.',
      location: 'Flame Peak, Góry Olbrzyma.',
      mapDesc: 'Północne Góry Olbrzyma przy Flame Peak.',
      grace: 'Obóz: U podnóża Kuźni.',
      strategy: ['Cała walka na Torrent', 'Celuj w kostkę z bleed/frost', 'Kula śniegu: jedź prostopadle', 'Przywołaj ducha gdy ty na koniu', 'Wielki łuk z konia'] },
    de: { name: 'Feuerriese', quote: '"Verbrenne... den Erdbaum..."', region: 'Flammengipfel',
      lore: 'Der letzte Feuerriese, der seine Sippe verriet um dem Erdbaum zu dienen. Bewacht die Flamme der Verwüstung.',
      location: 'Flammengipfel, Berggipfel der Riesen.',
      mapDesc: 'Nördliche Berggipfel der Riesen am Flammengipfel.',
      grace: 'Sammelpunkt: Fuß der Schmiede.',
      strategy: ['Ganzer Kampf auf Torrent', 'Knöchel mit Blutung/Frost', 'Schneeballphase: quer reiten', 'Geisterasche zu Fuß während du reitest', 'Großbogen vom Pferd'] }
  },

  {
    id: 'mohg', category: 'shard',
    image: './img/mohg.webp',
    en: { name: 'Mohg, Lord of Blood', quote: '"Nihil, nihil, nihil..."', region: 'Siofra River / Mohgwyn Palace',
      lore: 'Mohg is an Omen demigod who stole Miquella and founded the Mohgwyn Dynasty beneath the Lands Between. He worships the Formless Mother and seeks to elevate Miquella to godhood through blood rituals.',
      location: 'Mohgwyn Dynasty Mausoleum, accessed via White Mask questline or item from bloodied finger.',
      mapDesc: 'Deep underground in Mohgwyn Palace, far west of the map through a blood portal from Siofra.',
      grace: 'Nearest Site of Grace: Dynasty Mausoleum Entrance.',
      strategy: ['Use Mohg\'s Shackle twice at fight start', 'Purifying Crystal Tear removes blood curse buildup', 'Bloodhound Step dodges trident thrusts', 'Stay aggressive in phase 1 before blood wings grow', 'Bleed-resistant armor and Lord of Blood\'s Exultation help'] },
    pl: { name: 'Mohg, Pan Krwi', quote: '"Nihil, nihil, nihil..."', region: 'Pałac Mohgwyn',
      lore: 'Mohg to Omen który ukradł Miquellę i założył Dynastię Mohgwyn. Czcí Bezforemna Matkę.',
      location: 'Mauzoleum Dynastii Mohgwyn, przez quest Białej Maski.',
      mapDesc: 'Głęboko pod ziemią na zachodzie mapy.',
      grace: 'Obóz: Wejście do Mauzoleum Dynastii.',
      strategy: ['Kajdanki Mohga 2x na start', 'Purifying Crystal Tear usuwa klątwę krwi', 'Bloodhound Step na trójząb', 'Agresja w fazie 1', 'Pancerz odporny na krwawienie'] },
    de: { name: 'Mohg, Herr des Blutes', quote: '"Nihil, nihil, nihil..."', region: 'Mohgwyn-Palast',
      lore: 'Mohg stahl Miquella und gründete die Mohgwyn-Dynastie. Er dient der formlosen Mutter.',
      location: 'Mausoleum der Mohgwyn-Dynastie via Weißmasken-Quest.',
      mapDesc: 'Tief unterirdisch im Westen der Karte.',
      grace: 'Sammelpunkt: Mausoleumseingang der Dynastie.',
      strategy: ['Mohgs Fessel 2x zu Beginn', 'Reinigender Kristalltränke gegen Blutfluch', 'Bloodhound Step gegen Dreizack', 'Aggressiv in Phase 1', 'Blutresistente Rüstung'] }
  },
    {
    id: 'fortissax', category: 'legend',
    image: './img/lichdragon.webp',
    en: { name: 'Lichdragon Fortissax', quote: '"..."', region: 'Crumbling Farum Azula',
      lore: 'Fortissax was Godwyn\'s companion dragon who became a lich after the Death Rune was stolen. Fia\'s quest leads to this battle in a dream realm where lightning and death intertwine.',
      location: 'Deeper Depths via Fia\'s questline. Use the Twinned Set item on Godwyn\'s body.',
      mapDesc: 'Hidden boss in Crumbling Farum Azula accessed through Fia\'s quest after giving her the Twinned Set.',
      grace: 'Nearest Site of Grace: Crumbling Beast Grave Depths.',
      strategy: ['Use Lightning Spear or Bolt of Gransax — dragon is weak to lightning', 'Stay near Fortissax\'s head for most attacks', 'Death lightning wave: run sideways', 'Phase 2 death grip: roll forward not backward', 'Greatshield with Lightning Shield ash works well'] },
    pl: { name: 'Fortissax, Smoczy Lich', quote: '"..."', region: 'Farum Azula',
      lore: 'Fortissax był smokiem towarzyszem Godwyna, który stał się lichem po kradzieży Runy Śmierci.',
      location: 'Głębsze Głębiny przez quest Fii.',
      mapDesc: 'Ukryty boss w Farum Azula przez quest Fii.',
      grace: 'Obóz: Głębokie Groby Bestii.',
      strategy: ['Lightning Spear — smok słaby na pioruny', 'Przy głowie przez większość walki', 'Fala śmierci: bok', 'Chwyt śmierci: przetaczaj do przodu', 'Tarcza z Lightning Shield'] },
    de: { name: 'Lichdrache Fortissax', quote: '"..."', region: 'Farum Azula',
      lore: 'Fortissax war Godwyns Begleiterdrache und wurde ein Lich nach dem Diebstahl der Todesrune.',
      location: 'Tiefere Tiefen via Fias Quest.',
      mapDesc: 'Versteckter Boss in Farum Azula via Fias Quest.',
      grace: 'Sammelpunkt: Verfallenes Bestiengrab.',
      strategy: ['Blitzspeer — Drache schwach gegen Blitz', 'Nahe am Kopf bleiben', 'Todesblitzwelle: seitlich', 'Todesgriff: vorwärts rollen', 'Schild mit Blitzschild'] }
  },
    {
    id: 'placidusax', category: 'legend',
    image: './img/pla.webp',
    en: { name: 'Dragonlord Placidusax', quote: '"..."', region: 'Crumbling Farum Azula',
      lore: 'Placidusax was Elden Lord before the Erdtree age, a dragonlord who fought from the skies alongside his dragon. He awaits in a timeless dimension, a remnant of an era before Marika\'s rule.',
      location: 'Crumbling Farum Azula — lie down at the Placidusax fog gate near the Great Bridge.',
      mapDesc: 'Hidden in Farum Azula beyond a special fog wall. Accessible by interacting with the golden light near the bridge.',
      grace: 'Nearest Site of Grace: Beside the Great Bridge.',
      strategy: ['Use Lightning or Dragon Communion spells for bonus damage', 'Stay near his left claw for safest positioning', 'Lightning strike phase: run to opposite side of arena', 'Bloodhound Step through claw swipes', 'Phase 2: destroy both heads quickly with jump attacks'] },
    pl: { name: 'Placidusax, Władca Smoków', quote: '"..."', region: 'Farum Azula',
      lore: 'Placidusax był Panem Elden przed erą Drzewa Erd, władcą smoków walczącym z nieba.',
      location: 'Farum Azula — połóż się przy mgle Placidusax.',
      mapDesc: 'Ukryty w Farum Azula za specjalną mgłą przy moście.',
      grace: 'Obóz: Obok Wielkiego Mostu.',
      strategy: ['Piorun lub Dragon Communion', 'Przy lewym pazurze', 'Faza pioruna: na przeciwną stronę', 'Bloodhound Step na pazury', 'Faza 2: niszcz obie głowy'] },
    de: { name: 'Drachenfürst Placidusax', quote: '"..."', region: 'Farum Azula',
      lore: 'Placidusax war Eldenherr vor dem Erdbaum-Zeitalter und kämpfte vom Himmel.',
      location: 'Farum Azula — bei Placidusax-Nebel niederlegen.',
      mapDesc: 'Versteckt in Farum Azula hinter Nebelwand an der Brücke.',
      grace: 'Sammelpunkt: Neben der Großen Brücke.',
      strategy: ['Blitz oder Drachenkommunion', 'Nahe linker Klaue', 'Blitzphase: andere Seite', 'Bloodhound Step bei Klauen', 'Phase 2: beide Köpfe zerstören'] }
  },
  {
    id: 'malenia', category: 'shard',
    image: './img/malenia.webp',
    en: { name: 'Malenia, Blade of Miquella', quote: '"I am Malenia, Blade of Miquella."', region: 'Haligtree',
      lore: 'Malenia is the goddess of rot and the most formidable shardbearer. Born with Scarlet Rot, she never knew defeat until Radahn. She waits at the Haligtree protecting her brother Miquella, wielding prosthetics and waterfowl dance techniques.',
      location: 'Miquella\'s Haligtree, Elphael Brace of the Haligtree. Requires two Secret Medallion halves.',
      mapDesc: 'Far north beyond Mountaintops of the Giants. Use Grand Lift of Rold with Haligtree Secret Medallion.',
      grace: 'Nearest Site of Grace: Haligtree Roots or Prayer Room.',
      strategy: ['Bloodhound Step is almost mandatory for Waterfowl Dance', 'Use Greatshield + Barricade for blockable attacks', 'Scarlet Rot resistant gear (Lion\'s Greatbow approach)', 'Phase 2: Bloodhound Step through hyper armor clone attack', 'Summon Mimic Tear or Black Knife Tiche for aggro split', 'Lightning or Frost weapons work well'] },
    pl: { name: 'Malenia, Ostrze Miquelli', quote: '"Jestem Malenia, Ostrze Miquelli."', region: 'Haligtree',
      lore: 'Malenia to bogini zgnilizny i najpotężniejszy nosiciel odłamka. Nigdy nie znała porażki aż do Radahna.',
      location: 'Haligtree Miquelli, wymaga dwóch połówek Tajnego Medalionu.',
      mapDesc: 'Daleko na północy za Górami Olbrzyma.',
      grace: 'Obóz: Korzenie Haligtree.',
      strategy: ['Bloodhound Step prawie obowiązkowy na Waterfowl Dance', 'Wielka tarcza + Barricade', 'Odporność na Scarlet Rot', 'Bloodhound Step przez klon w fazie 2', 'Mimic Tear na aggro', 'Broń z piorunem lub mrozem'] },
    de: { name: 'Malenia, Klinge Miquellas', quote: '"Ich bin Malenia, Klinge Miquellas."', region: 'Haligbaum',
      lore: 'Malenia ist die Göttin der Fäulnis und stärkster Scherbenhüter. Sie blieb unbesiegt bis Radahn.',
      location: 'Miquellas Haligbaum, benötigt zwei Geheimmedaillon-Hälften.',
      mapDesc: 'Weit im Norden jenseits der Berggipfel der Riesen.',
      grace: 'Sammelpunkt: Haligbaumwurzeln.',
      strategy: ['Bloodhound Step für Waterfowl Dance fast Pflicht', 'Großschild + Barricade', 'Scharlachfäule-Resistenz', 'Bloodhound Step durch Klon in Phase 2', 'Mimic Tear für Aggro', 'Blitz- oder Frostwaffen'] }
  },
  {
    id: 'maliketh', category: 'shard',
    image: './img/Maliketh.webp',
    en: { name: 'Maliketh, the Black Blade', quote: '"Destined Death, unleashed."', region: 'Crumbling Farum Azula',
      lore: 'Maliketh is the shadow of Marika and vessel of Destined Death, sealed within the Black Blade. He guards the Rune of Death in Farum Azula, a floating ruin beyond time where Gwyn\'s kin once dwelled.',
      location: 'Crumbling Farum Azula, after burning the Erdtree. Defeat Godskin Duo first.',
      mapDesc: 'Floating ruins accessed after Leyndell becomes Ashen Capital. Southeast of the map in the sky.',
      grace: 'Nearest Site of Grace: Beside the Great Bridge or Dragonlord Placidusax fog gate area.',
      strategy: ['Use Bestial Incantations — they deal bonus damage to Maliketh', 'Phase 1 (Gideon\'s beast form): learn attack patterns first', 'Bloodhound Step for black blade wave attacks', 'Blasphemous Blade weapon skill heals during fight', 'Stay close in phase 2 to prevent gap-closing jump attacks'] },
    pl: { name: 'Maliketh, Czarne Ostrze', quote: '"Przeznaczona Śmierć, uwolniona."', region: 'Farum Azula',
      lore: 'Maliketh to cień Mariki i nosiciel Przeznaczonej Śmierci. Strzeże Runy Śmierci w Farum Azula.',
      location: 'Ruiny Farum Azula po spaleniu Drzewa Erd.',
      mapDesc: 'Latające ruiny na południowym wschodzie mapy.',
      grace: 'Obóz: Obok Wielkiego Mostu.',
      strategy: ['Bestial Incantations dają bonus', 'Naucz się wzorców fazy 1', 'Bloodhound Step na fale ostrza', 'Blasphemous Blade leczy', 'Blisko w fazie 2'] },
    de: { name: 'Maliketh, die Schwarze Klinge', quote: '"Bestimmter Tod, entfesselt."', region: 'Farum Azula',
      lore: 'Maliketh ist Marikas Schatten und Träger des bestimmten Todes in Farum Azula.',
      location: 'Verfallene Farum Azula nach dem Erdbaumbrand.',
      mapDesc: 'Schwebende Ruinen im Südosten der Karte.',
      grace: 'Sammelpunkt: Neben der Großen Brücke.',
      strategy: ['Bestien-Inkanationen Bonus-Schaden', 'Phase-1-Muster lernen', 'Bloodhound Step gegen Klingenwellen', 'Blasphemous Blade heilt', 'Nah in Phase 2 bleiben'] }
  },
  {
    id: 'godfrey', category: 'shard',
    image: './img/godfrey1.webp',
    en: { name: 'Godfrey, First Elden Lord', quote: '"A warrior, after all."', region: 'Leyndell, Ashen Capital',
      lore: 'Godfrey was the first Elden Lord and consort of Queen Marika. Stripped of grace after becoming Hoarah Loux, he returned as a Tarnished to reclaim his throne, bearing the scars of countless battles and the spirit of a true warrior.',
      location: 'Erdtree Sanctuary, Leyndell Ashen Capital. After burning the Erdtree.',
      mapDesc: 'Same location as Morgott but in the ashen ruins of Leyndell after the Erdtree burns.',
      grace: 'Nearest Site of Grace: Queen\'s Bedchamber.',
      strategy: ['Use Barricade Shield Ash on Greatshield for phase 1', 'Roll toward grab attacks to dodge', 'Phase 2 Hoarah Loux: stay mid-range and punish roars', 'Bloodhound Step for stomp combo', 'Do NOT panic during long axe combo — last hit is delayed'] },
    pl: { name: 'Godfrey, Pierwszy Pan Elden', quote: '"Wojownik, w końcu."', region: 'Popiół Leyndell',
      lore: 'Godfrey był pierwszym Panem Elden i małżonkiem Mariki. Wrócił jako Zhańbiony by odzyskać tron.',
      location: 'Sanktuarium Drzewa Erd, Popiół Leyndell.',
      mapDesc: 'Ruiny Leyndell po spaleniu Drzewa Erd.',
      grace: 'Obóz: Komnata Królowej.',
      strategy: ['Barricade Shield w fazie 1', 'Przetaczaj się w chwyt', 'Faza 2: kara za ryki', 'Bloodhound Step na combo', 'Ostatni cios opóźniony — nie panikuj'] },
    de: { name: 'Godfrey, Erster Eldenherr', quote: '"Ein Krieger, schließlich."', region: 'Verbrannte Leyndell',
      lore: 'Godfrey war Marikas erster Eldenherr. Er kehrte als Befleckter zurück, um seinen Thron zu erobern.',
      location: 'Erdbaumsanktuar, Verbrannte Leyndell.',
      mapDesc: 'Ruinen von Leyndell nach dem Erdbaumbrand.',
      grace: 'Sammelpunkt: Königinnenschlafgemach.',
      strategy: ['Barricade Shield in Phase 1', 'In Greifattacken rollen', 'Phase 2: Brüllen bestrafen', 'Bloodhound Step bei Stampfcombo', 'Letzter Schlag verzögert'] }
  },
  {
    id: 'radagon', category: 'final',
    image: './img/Radagon.webp',
    en: { name: 'Radagon of the Golden Order', quote: '"The Golden Order has no flaws."', region: 'Fractured Marika',
      lore: 'Radagon is the other half of Marika, once leader of the Golden Order and consort who became one with the Elden Queen. When the Elden Ring shattered, Radagon attempted to repair it, becoming the final obstacle before the throne.',
      location: 'Stone Platform after defeating Maliketh and reaching the Fractured Marika arena.',
      mapDesc: 'The final arena at the base of the Erdtree after completing Crumbling Farum Azula.',
      grace: 'Site of Grace appears after defeating both Radagon and Elden Beast.',
      strategy: ['Holy damage negated — use physical or fire weapons', 'Hammer swings: roll TOWARD Radagon not away', 'Lightning bolts: run diagonally not straight', 'Phase transitions are free heal windows', 'Bloodhound Step is excellent for hammer combos'] },
    pl: { name: 'Radagon Złotego Porządku', quote: '"Złoty Porządek nie ma wad."', region: 'Fractured Marika',
      lore: 'Radagon to druga połowa Mariki, przywódca Złotego Porządku. Próbuje naprawić Pierścień Elden.',
      location: 'Kamienna Platforma po Maliketh.',
      mapDesc: 'Ostatnia arena u podstawy Drzewa Erd.',
      grace: 'Obóz pojawia się po pokonaniu obu bossów.',
      strategy: ['Obrażenia święte niewskazane — fizyczne lub ogień', 'Przetaczaj się w stronę młota', 'Pioruny: biegnij ukośnie', 'Przejścia faz to okno na leczenie', 'Bloodhound Step na combo'] },
    de: { name: 'Radagon des Goldenen Ordens', quote: '"Der Goldene Orden hat keine Fehler."', region: 'Fractured Marika',
      lore: 'Radagon ist Marikas andere Hälfte und Anführer des Goldenen Ordens. Er versucht den Eldenring zu reparieren.',
      location: 'Steinplattform nach Maliketh.',
      mapDesc: 'Finale Arena am Fuß des Erdbaums.',
      grace: 'Sammelpunkt erscheint nach beiden Bossen.',
      strategy: ['Heiliger Schaden nutzlos — physisch oder Feuer', 'In Hammerhiebe rollen', 'Blitze diagonal ausweichen', 'Phasenwechsel zum Heilen', 'Bloodhound Step für Combos'] }
  },
  {
    id: 'elden-beast', category: 'final',
    image: './img/beast.webp',
    en: { name: 'Elden Beast', quote: '"..."', region: 'Fractured Marika',
      lore: 'The Elden Beast is the vassal beast of the Greater Will and true form of the Elden Ring\'s guardian. It manifests after Radagon falls, representing the cosmic will that binds the Lands Between to outer gods.',
      location: 'Immediately after defeating Radagon on the same arena.',
      mapDesc: 'Same arena as Radagon — phase 2 of the final encounter at the Erdtree base.',
      grace: 'Site of Grace: Fractured Marika appears after victory.',
      strategy: ['Use Black Flame incantations or Destined Death weapons', 'Holy damage is fully resisted — avoid Faith builds', 'Run toward the beast when it flies away', 'Elden Stars: run in wide circles', 'Black Knife Tiche or Mimic Tear for aggro', 'Phase 2 ring attack: jump or roll through gaps'] },
    pl: { name: 'Bestia Elden', quote: '"..."', region: 'Fractured Marika',
      lore: 'Bestia Elden to sługa Wielkiej Woli i strażnik Pierścienia Elden. Manifestuje się po upadku Radagona.',
      location: 'Bezpośrednio po Radagonie na tej samej arenie.',
      mapDesc: 'Ta sama arena co Radagon — faza 2 finału.',
      grace: 'Obóz: Fractured Marika po zwycięstwie.',
      strategy: ['Black Flame lub Destined Death', 'Unikaj obrażeń świętych', 'Biegnij gdy bestia odlatuje', 'Elden Stars: biegnij w kółko', 'Black Knife Tiche na aggro', 'Przetaczaj się przez pierścienie'] },
    de: { name: 'Eldenbestie', quote: '"..."', region: 'Fractured Marika',
      lore: 'Die Eldenbestie ist Diener des Größeren Willens und Wächter des Eldenrings.',
      location: 'Direkt nach Radagon auf derselben Arena.',
      mapDesc: 'Gleiche Arena wie Radagon — Phase 2 des Finales.',
      grace: 'Sammelpunkt: Fractured Marika nach Sieg.',
      strategy: ['Schwarze Flamme oder Bestimmter Tod', 'Heiliger Schaden vermeiden', 'Zur Bestie rennen wenn sie fliegt', 'Elden Stars: im Kreis laufen', 'Black Knife Tiche für Aggro', 'Durch Ringlücken rollen'] }
  },









];

window.ER_BUILDS = [
  {
    id: 'bloodhound-fang', type: 'dexterity',
   
    en: { name: 'Bloodhound Fang Dex', typeLabel: 'Dexterity / Bleed', playstyle: 'Aggressive melee with sustained DPS and mobility',
      weapon: 'Bloodhound\'s Fang +25 (Cursemark of Death affinity optional)',
      ash: 'Bloodhound\'s Finesse (default weapon art)',
      helmet: 'Radahn\'s Helm', armor: 'Radahn\'s Chest', gloves: 'Radahn\'s Gauntlets', legs: 'Radahn\'s Greaves',
      talismans: 'Rotten Winged Sword Insignia · Lord of Blood\'s Exultation · Green Turtle Talisman · Dragoncrest Greatshield Talisman',
      stats: 'Vigor 50 · Endurance 30 · Strength 18 · Dexterity 40 · Arcane 20' },
    pl: { name: 'Bloodhound Fang Dex', typeLabel: 'Zręczność / Krwawienie', playstyle: 'Agresywny melee z mobilnością',
      weapon: 'Bloodhound\'s Fang +25', ash: 'Bloodhound\'s Finesse',
      helmet: 'Hełm Radahna', armor: 'Zbroja Radahna', gloves: 'Rękawice Radahna', legs: 'Nogi Radahna',
      talismans: 'Rotten Winged Sword Insignia · Lord of Blood\'s Exultation · Green Turtle · Dragoncrest Greatshield',
      stats: 'Vigor 50 · Endurance 30 · Strength 18 · Dexterity 40 · Arcane 20' },
    de: { name: 'Bloodhound Fang Dex', typeLabel: 'Geschick / Blutung', playstyle: 'Aggressives Nahkampf mit Mobilität',
      weapon: 'Bloodhound\'s Fang +25', ash: 'Bloodhound\'s Finesse',
      helmet: 'Radahns Helm', armor: 'Radahns Brust', gloves: 'Radahns Handschuhe', legs: 'Radahns Beinschienen',
      talismans: 'Rotten Winged Sword Insignia · Lord of Blood\'s Exultation · Green Turtle · Dragoncrest Greatshield',
      stats: 'Vigor 50 · Endurance 30 · Strength 18 · Dexterity 40 · Arcane 20' }
  },
  {
    id: 'blasphemous', type: 'faith',
   
    en: { name: 'Blasphemous Blade Faith', typeLabel: 'Faith / Sustain', playstyle: 'Balanced sword with self-healing weapon art',
      weapon: 'Blasphemous Blade +25 (Sacred affinity)',
      ash: 'Taker\'s Flames (heals on hit)',
      helmet: 'Veteran\'s Helm', armor: 'Veteran\'s Armor', gloves: 'Veteran\'s Gauntlets', legs: 'Veteran\'s Greaves',
      talismans: 'Faithful\'s Canvas Talisman · Green Turtle · Dragoncrest Greatshield · Erdtree\'s Favor +2',
      stats: 'Vigor 55 · Mind 20 · Endurance 30 · Strength 30 · Faith 50' },
    pl: { name: 'Blasphemous Blade Wiara', typeLabel: 'Wiara / Leczenie', playstyle: 'Miecz z leczeniem z umiejętności broni',
      weapon: 'Blasphemous Blade +25', ash: 'Taker\'s Flames',
      helmet: 'Hełm Weterana', armor: 'Zbroja Weterana', gloves: 'Rękawice Weterana', legs: 'Nogi Weterana',
      talismans: 'Faithful\'s Canvas · Green Turtle · Dragoncrest · Erdtree\'s Favor +2',
      stats: 'Vigor 55 · Mind 20 · Endurance 30 · Strength 30 · Faith 50' },
    de: { name: 'Blasphemous Blade Glaube', typeLabel: 'Glaube / Heilung', playstyle: 'Schwert mit Heilung durch Waffenkunst',
      weapon: 'Blasphemous Blade +25', ash: 'Taker\'s Flames',
      helmet: 'Veteranenhelm', armor: 'Veteranenrüstung', gloves: 'Veteranenhandschuhe', legs: 'Veteranenbeinschienen',
      talismans: 'Faithful\'s Canvas · Green Turtle · Dragoncrest · Erdtree\'s Favor +2',
      stats: 'Vigor 55 · Mind 20 · Endurance 30 · Strength 30 · Faith 50' }
  },
  {
    id: 'moonveil', type: 'intelligence',

    en: { name: 'Moonveil Mage', typeLabel: 'Intelligence / Hybrid', playstyle: 'Fast katana with magic burst damage',
      weapon: 'Moonveil +25 (Magic affinity)',
      ash: 'Transient Moonlight',
      helmet: 'Azur\'s Glintstone Crown', armor: 'Snow Witch Robe', gloves: 'Snow Witch Skirt (arms)', legs: 'Snow Witch Skirt',
      talismans: 'Radicon Icon · Magic Scorpion Charm · Graven-School Talisman · Cerulean Hidden Tear (in flask)',
      stats: 'Vigor 40 · Mind 30 · Endurance 20 · Dexterity 18 · Intelligence 60' },
    pl: { name: 'Moonveil Mag', typeLabel: 'Inteligencja / Hybryda', playstyle: 'Szybka katana z magicznymi burstami',
      weapon: 'Moonveil +25', ash: 'Transient Moonlight',
      helmet: 'Korona Azura', armor: 'Szata Śnieżnej Wiedźmy', gloves: 'Spódnica Wiedźmy', legs: 'Spódnica Wiedźmy',
      talismans: 'Radicon Icon · Magic Scorpion · Graven-School · Cerulean Hidden Tear',
      stats: 'Vigor 40 · Mind 30 · Endurance 20 · Dexterity 18 · Intelligence 60' },
    de: { name: 'Moonveil Magier', typeLabel: 'Intelligenz / Hybrid', playstyle: 'Schnelle Katana mit Magie-Burst',
      weapon: 'Moonveil +25', ash: 'Transient Moonlight',
      helmet: 'Azurs Glintsteinkrone', armor: 'Schneehexenrobe', gloves: 'Schneehexenrock', legs: 'Schneehexenrock',
      talismans: 'Radicon Icon · Magic Scorpion · Graven-School · Cerulean Hidden Tear',
      stats: 'Vigor 40 · Mind 30 · Endurance 20 · Dexterity 18 · Intelligence 60' }
  },
  {
    id: 'greatsword-str', type: 'strength',
  
    en: { name: 'Greatsword Strength', typeLabel: 'Strength / Poise', playstyle: 'Hyper armor trading with massive damage',
      weapon: 'Greatsword +25 (Heavy affinity, dual-wield power stance)',
      ash: 'Determination or Royal Knight\'s Resolve',
      helmet: 'Bull-Goat Helm', armor: 'Bull-Goat Armor', gloves: 'Bull-Goat Gauntlets', legs: 'Bull-Goat Greaves',
      talismans: 'Green Turtle · Arsenal Charm · Dragoncrest Greatshield · Great-Jar\'s Arsenal',
      stats: 'Vigor 60 · Endurance 35 · Strength 54 · Dexterity 16' },
    pl: { name: 'Greatsword Siła', typeLabel: 'Siła / Poise', playstyle: 'Hyper armor i ogromne obrażenia',
      weapon: 'Greatsword +25 (Heavy, power stance)', ash: 'Determination',
      helmet: 'Hełm Bull-Goat', armor: 'Zbroja Bull-Goat', gloves: 'Rękawice Bull-Goat', legs: 'Nogi Bull-Goat',
      talismans: 'Green Turtle · Arsenal Charm · Dragoncrest · Great-Jar\'s Arsenal',
      stats: 'Vigor 60 · Endurance 35 · Strength 54 · Dexterity 16' },
    de: { name: 'Greatsword Stärke', typeLabel: 'Stärke / Poise', playstyle: 'Hyper-Rüstung mit massivem Schaden',
      weapon: 'Greatsword +25 (Heavy, Power Stance)', ash: 'Determination',
      helmet: 'Bockziegen-Helm', armor: 'Bockziegen-Rüstung', gloves: 'Bockziegen-Handschuhe', legs: 'Bockziegen-Beinschienen',
      talismans: 'Green Turtle · Arsenal Charm · Dragoncrest · Great-Jar\'s Arsenal',
      stats: 'Vigor 60 · Endurance 35 · Strength 54 · Dexterity 16' }
  },
  {
    id: 'rivers', type: 'arcane',
    
    en: { name: 'Rivers of Blood Arcane', typeLabel: 'Arcane / Bleed', playstyle: 'Fast katana stack with Corpse Piler art',
      weapon: 'Rivers of Blood +25 (occult scaling)',
      ash: 'Corpse Piler',
      helmet: 'White Mask', armor: 'Lord of Blood\'s Robe', gloves: 'Lord of Blood\'s Gauntlets', legs: 'Lord of Blood\'s Greaves',
      talismans: 'Lord of Blood\'s Exultation · Rotten Winged Sword Insignia · Millicent\'s Prosthesis · Dragoncrest Shield',
      stats: 'Vigor 45 · Endurance 30 · Dexterity 20 · Arcane 80' },
    pl: { name: 'Rivers of Blood Arkana', typeLabel: 'Arkana / Krwawienie', playstyle: 'Szybka katana z Corpse Piler',
      weapon: 'Rivers of Blood +25', ash: 'Corpse Piler',
      helmet: 'Biała Maska', armor: 'Szata Pana Krwi', gloves: 'Rękawice Pana Krwi', legs: 'Nogi Pana Krwi',
      talismans: 'Lord of Blood\'s Exultation · Rotten Winged · Millicent\'s Prosthesis · Dragoncrest Shield',
      stats: 'Vigor 45 · Endurance 30 · Dexterity 20 · Arcane 80' },
    de: { name: 'Rivers of Blood Arkan', typeLabel: 'Arkan / Blutung', playstyle: 'Schnelle Katana mit Corpse Piler',
      weapon: 'Rivers of Blood +25', ash: 'Corpse Piler',
      helmet: 'Weiße Maske', armor: 'Roben des Blutherrn', gloves: 'Handschuhe des Blutherrn', legs: 'Beinschienen des Blutherrn',
      talismans: 'Lord of Blood\'s Exultation · Rotten Winged · Millicent\'s Prosthesis · Dragoncrest Shield',
      stats: 'Vigor 45 · Endurance 30 · Dexterity 20 · Arcane 80' }
  },
  {
    id: 'death-poker', type: 'intelligence',
    
    en: { name: 'Death\'s Poker Frost Mage', typeLabel: 'Intelligence / Frost', playstyle: 'Great spear with ghostflame frost explosions',
      weapon: 'Death\'s Poker +25 (Magic affinity)',
      ash: 'Ghostflame Ignition',
      helmet: 'Azur\'s Glintstone Crown', armor: 'Lusat\'s Robe', gloves: 'Lusat\'s Manchettes', legs: 'Old Sorcerer\'s Legwraps',
      talismans: 'Graven-Mass Talisman · Magic Scorpion · Radicon Icon · Cerulean Hidden Tear',
      stats: 'Vigor 45 · Mind 35 · Endurance 20 · Strength 18 · Intelligence 70' },
    pl: { name: 'Death\'s Poker Frost', typeLabel: 'Inteligencja / Mróz', playstyle: 'Włócznia z ghostflame i mrozem',
      weapon: 'Death\'s Poker +25', ash: 'Ghostflame Ignition',
      helmet: 'Korona Azura', armor: 'Szata Lusata', gloves: 'Manchette Lusata', legs: 'Owijacze Starego Czarodzieja',
      talismans: 'Graven-Mass · Magic Scorpion · Radicon Icon · Cerulean Hidden Tear',
      stats: 'Vigor 45 · Mind 35 · Endurance 20 · Strength 18 · Intelligence 70' },
    de: { name: 'Death\'s Poker Frost', typeLabel: 'Intelligenz / Frost', playstyle: 'Speer mit Geisterflammen-Frost',
      weapon: 'Death\'s Poker +25', ash: 'Ghostflame Ignition',
      helmet: 'Azurs Krone', armor: 'Lusats Robe', gloves: 'Lusats Manschetten', legs: 'Alte Zauberbeinschienen',
      talismans: 'Graven-Mass · Magic Scorpion · Radicon Icon · Cerulean Hidden Tear',
      stats: 'Vigor 45 · Mind 35 · Endurance 20 · Strength 18 · Intelligence 70' }
  },
  // ─── ONE-SHOT BUILD ────────────────────────────────────────────────────────
  {
    id: 'giant-crusher', type: 'strength',
   
    en: {
      name: 'One-Shot Giant-Crusher',
      typeLabel: 'Strength / One-Shot',
      playstyle: 'Stack every buff, trigger bleed on yourself, then delete anything with a fully-charged R2',
      weapon: 'Giant-Crusher +25 (Heavy affinity) — main hand two-handed',
      ash: 'Royal Knight\'s Resolve (doubles next attack damage)',
      helmet: 'Black Dumpling (boosts ATK when madness triggers) or White Mask',
      armor: 'Any heavy chest (Bull-Goat for max poise)',
      gloves: 'Any heavy gauntlets',
      legs: 'Any heavy greaves',
      talismans: 'Axe Talisman · Lord of Blood\'s Exultation · Two-Handed Sword Talisman · Red-Feathered Branchsword',
      stats: 'Vigor 60 · Endurance 40 · Strength 80 · Dexterity 18 · Faith 24',
    },
    pl: {
      name: 'One-Shot Giant-Crusher',
      typeLabel: 'Siła / One-Shot',
      playstyle: 'Nałóż wszystkie buffy, wywołaj krwawienie na sobie, skasuj przeciwnika naładowanym R2',
      weapon: 'Giant-Crusher +25 (Heavy) — trzymaj oburącz',
      ash: 'Royal Knight\'s Resolve (podwaja obrażenia następnego ataku)',
      helmet: 'Black Dumpling (boost ATK przy obłędzie) lub White Mask',
      armor: 'Ciężka zbroja (Bull-Goat dla max poise)',
      gloves: 'Ciężkie rękawice',
      legs: 'Ciężkie nagolenniki',
      talismans: 'Axe Talisman · Lord of Blood\'s Exultation · Two-Handed Sword Talisman · Red-Feathered Branchsword',
      stats: 'Vigor 60 · Endurance 40 · Strength 80 · Dexterity 18 · Faith 24',
      buffSequence: [
        'Rzuć Golden Vow (inkantacja — podnosi ATK i DEF)',
        'Rzuć Flame, Grant Me Strength lub Howl of Shabiri',
        'Użyj Seppuku na sztylecie w lewej ręce — krwawienie na sobie aktywuje Lord of Blood\'s Exultation',
        'Wypij Cudowny Flakon: Spiked Cracked Tear + Strength-knot Crystal Tear',
        'Zejdź do niskiego HP (aktywuje Red-Feathered Branchsword)',
        'Trzymaj Giant-Crusher oburącz, aktywuj Royal Knight\'s Resolve',
        'Wypuść naładowane R2 — one-shot gwarantowany'
      ]
    },
    de: {
      name: 'One-Shot Giant-Crusher',
      typeLabel: 'Stärke / One-Shot',
      playstyle: 'Alle Buffs stapeln, Blutung an dir selbst auslösen, dann alles mit geladenem R2 auslöschen',
      weapon: 'Giant-Crusher +25 (Heavy) — beidhändig gehalten',
      ash: 'Royal Knight\'s Resolve (verdoppelt nächsten Angriff)',
      helmet: 'Black Dumpling (ATK-Boost bei Wahnsinn) oder White Mask',
      armor: 'Schwere Rüstung (Bull-Goat für maximalen Poise)',
      gloves: 'Schwere Handschuhe',
      legs: 'Schwere Beinschienen',
      talismans: 'Axe Talisman · Lord of Blood\'s Exultation · Two-Handed Sword Talisman · Red-Feathered Branchsword',
      stats: 'Vigor 60 · Endurance 40 · Strength 80 · Dexterity 18 · Faith 24',
      buffSequence: [
        'Golden Vow wirken (erhöht ATK und DEF)',
        'Flame, Grant Me Strength oder Howl of Shabiri wirken',
        'Seppuku auf Offhand-Dolch anwenden — Blutverlust an sich selbst, aktiviert Lord of Blood\'s Exultation',
        'Wundertrank trinken: Spiked Cracked Tear + Strength-knot Crystal Tear',
        'Auf niedrige HP fallen (Red-Feathered Branchsword aktiv)',
        'Giant-Crusher beidhändig halten, Royal Knight\'s Resolve aktivieren',
        'Geladenes R2 ausführen — One-Shot garantiert'
      ]
    }
  }
];
